version: '3.8'

services:
  web:
    build: ./main
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./main:/main
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydb
volumes:
  postgres_data: